// Color themes for NumiLand Adventure.
// All themes are bright, soft and child-friendly. No dark or aggressive tones.

export const THEMES = {
  sunny: {
    key: 'sunny',
    label: 'Sunny',
    background: '#FFF9E8',
    card: '#FFFFFF',
    primary: '#FFC857',
    primaryDark: '#F4A93B',
    secondary: '#7EC8E3',
    accent: '#FF9AA2',
    text: '#5A4A2F',
    textSoft: '#9B8B6E',
    success: '#7BC47F',
    error: '#FF9AA2',
    tile1: '#FFE3A3',
    tile2: '#BDE0FE',
    tile3: '#C8F7C5',
    tile4: '#FFC8DD',
    tile5: '#D8C5FF',
  },
  ocean: {
    key: 'ocean',
    label: 'Ocean',
    background: '#E8F7FB',
    card: '#FFFFFF',
    primary: '#5EC5D8',
    primaryDark: '#3DA9BD',
    secondary: '#9AD0EC',
    accent: '#7ED7C1',
    text: '#23566A',
    textSoft: '#6E97A6',
    success: '#5FC9A8',
    error: '#F4A3A8',
    tile1: '#BFE9F2',
    tile2: '#CDEAFB',
    tile3: '#C6F1E7',
    tile4: '#D6E9FF',
    tile5: '#BFE3E0',
  },
  candy: {
    key: 'candy',
    label: 'Candy',
    background: '#FFF0F6',
    card: '#FFFFFF',
    primary: '#FF8FB1',
    primaryDark: '#F26d97',
    secondary: '#C8A2F0',
    accent: '#FFC2D1',
    text: '#7A3B55',
    textSoft: '#B07E92',
    success: '#8AD98A',
    error: '#FF9AA2',
    tile1: '#FFD1E3',
    tile2: '#E7D1FF',
    tile3: '#FFE0C2',
    tile4: '#D1F0FF',
    tile5: '#FFC9DE',
  },
  space: {
    key: 'space',
    label: 'Space',
    background: '#EEF0FF',
    card: '#FFFFFF',
    primary: '#8E9BFF',
    primaryDark: '#6F7EF0',
    secondary: '#B7A6F0',
    accent: '#7ED7E8',
    text: '#3C3A6B',
    textSoft: '#8784A8',
    success: '#7BC47F',
    error: '#FF9AA2',
    tile1: '#D6DBFF',
    tile2: '#E2D6FF',
    tile3: '#CFE8FF',
    tile4: '#FFD9F0',
    tile5: '#D2F0F5',
  },
};

export const DEFAULT_THEME = 'sunny';

export function getTheme(key) {
  return THEMES[key] || THEMES[DEFAULT_THEME];
}
